export const CombatTimeControlConfig = {
  CHRONO_MAX: 100,
  CHRONO_START: 50,
  CHRONO_WAVE_RECOVERY: 20,
  CHRONO_IDLE_REGEN_PER_SECOND: 2,
  REWIND_CHRONO_DRAIN_PER_SECOND: 30,
  FAST_FORWARD_CHRONO_DRAIN_PER_SECOND: 20,
  REWIND_ROTATION_SPEED_MULTIPLIER: 4,
  FAST_FORWARD_ROTATION_SPEED_MULTIPLIER: 2,
} as const;
