export const CombatTimeControlConfig = {
  CHRONO_MAX: 100,
  CHRONO_START: 40,
  CHRONO_WAVE_RECOVERY: 15,
  CHRONO_IDLE_REGEN_PER_SECOND: 1,
  REWIND_CHRONO_DRAIN_PER_SECOND: 30,
  FAST_FORWARD_CHRONO_DRAIN_PER_SECOND: 20,
  REWIND_ROTATION_SPEED_MULTIPLIER: 4,
  FAST_FORWARD_ROTATION_SPEED_MULTIPLIER: 1.75,
} as const;
