export const CombatBalanceConfig = {
  BASE_HP: 100,
  PREVIEW_DURATION_MS: 1000,
  RECORD_START_ANGLE_DEG: 0,
  RECORD_ROTATION_SPEED_DEG_PER_SECOND: 30,
  NOTE_PACKET_CAPACITY: 5,
  SLOT_ACTIVATION_PULSE_DURATION_MS: 180,
  SLOT_ACTIVATION_MAX_ALPHA: 0.95,
} as const;
