export const CombatVisualConfig = {
  NOTE_COLORS: {
    red: 0xff5f7a,
    green: 0x63f5a6,
    blue: 0x5db7ff,
  },
  NOTE_PACKET: {
    SPACING_X: 25,
    STACK_RISE_Y: 6,
    FLOAT_AMPLITUDE_Y: 4,
    FLOAT_OUTER_NOTE_FALLOFF_Y: 1,
    FLOAT_PERIOD_MS: 1250,
    FLOAT_PHASE_STEP_RAD: (Math.PI * 2) / 3,
    FLOAT_PHASE_OFFSET_RAD: -Math.PI / 2,
    GLYPH_SCALE: 0.75,
  },
  TIME_CONTROL: {
    ACTIVE_GLOW_ALPHA: 0.9,
    INACTIVE_GLOW_ALPHA: 0.22,
    BAR_LOW_COLOR: 0x2c4457,
    BAR_FILL_COLOR: 0x66efff,
    BAR_ACTIVE_COLOR: 0xd6fe8d,
    BAR_FRAME_COLOR: 0x6fdcff,
    BAR_EMPTY_COLOR: 0x111927,
    LABEL_FONT_SIZE_PX: 15,
    GLYPH_FONT_SIZE_PX: 26,
    SPARK_INTERVAL_MS: 85,
    SPARK_LIFETIME_MS: 320,
    SPARK_MIN_SPEED_PX: 18,
    SPARK_MAX_SPEED_PX: 56,
  },
  EMPTY_SLOT_LABEL: 'EMPTY',
  RULE_LABEL_FONT_SIZE_PX: 22,
  EMPTY_LABEL_FONT_SIZE_PX: 14,
  TIER_STAR_FONT_SIZE_PX: 36,
  SLOT: {
    PEDESTAL_WIDTH: 112,
    PEDESTAL_HEIGHT: 20,
    CONSTRUCT_RADIUS: 34,
    STAR_OFFSET_Y: 55,
    INNER_ZONE_OFFSET_RATIO: 0.85,
    OUTER_ZONE_OFFSET_RATIO: 0.8,
  },
  ENEMY: {
    BASE_BODY_WIDTH: 31,
    BASE_BODY_HEIGHT: 36,
    KNOCKBACK_MAGNITUDE_PX: 100,
    SCALE_MULTIPLIERS: {
      basic: 1.0,
      tank: 1.6,
      fast: 0.7,
      ranged: 1.1,
      swarm: 0.5,
      boss: 2.5,
    },
    HEAD_SHAPES: {
      basic: 'triangle',
      tank: 'square',
      fast: 'oval',
      ranged: 'semicircle',
      swarm: 'diamond',
      boss: 'triangle-horned',
    },
    BODY_PRIMITIVES: {
      basic: ['rectangle', 'trapezoid'],
      tank: ['wide-rectangle', 'short-rectangle', 'short-rectangle'],
      fast: ['oval', 'v-shape'],
      ranged: ['hexagon', 'thin-rectangle'],
      swarm: ['capsule', 'short-leg', 'short-leg'],
      boss: ['rectangle', 'trapezoid', 'crown'],
    },
    HP_BAR_OFFSET_Y: -35,
    HP_BAR_WIDTH: 33,
    HP_BAR_HEIGHT: 8,
    HIT_FLASH_OFFSET_Y: -3,
    BODY_WIDTH: 31,
    BODY_HEIGHT: 36,
  },
  DAMAGE_NUMBER: {
    FONT_SIZE_PX: 14,
    FLOAT_DURATION_MS: 600,
    FLOAT_DISTANCE_Y: 30,
    BASE_OFFSET_X: 60,
    BASE_OFFSET_Y: -20,
    ENEMY_OFFSET_Y: -10,
  },
  ANIMATION: {
    IDLE_PULSE_PERIOD_MS: 1500,
    MOVE_HOP_PERIOD_MS: 400,
    ATTACK_FLASH_DURATION_MS: 150,
    HIT_FLASH_DURATION_MS: 80,
    DEATH_DURATION_MS: 300,
    DEATH_BOSS_DURATION_MS: 500,
    DEATH_SCALE_DELAY_RATIO: 0.18,
    DEATH_SCALE_EASE_POWER: 2.4,
    DEATH_KNOCKBACK_EASE_POWER: 3,
  },
} as const;
