export const CombatVisualConfig = {
  NOTE_COLORS: {
    red: 0xff5f7a,
    green: 0x63f5a6,
    blue: 0x5db7ff,
  },
  NOTE_PACKET: {
    SPACING_X: 28,
    STACK_RISE_Y: 6,
    BOUNCE_AMPLITUDE_Y: 6,
    BOUNCE_PERIOD_MS: 750,
    GLYPH_SCALE: 0.72,
  },
  EMPTY_SLOT_LABEL: 'EMPTY',
  RULE_LABEL_FONT_SIZE_PX: 18,
  EMPTY_LABEL_FONT_SIZE_PX: 14,
  TIER_STAR_FONT_SIZE_PX: 36,
  SLOT: {
    PEDESTAL_WIDTH: 112,
    PEDESTAL_HEIGHT: 20,
    CONSTRUCT_RADIUS: 34,
    STAR_OFFSET_Y: 55,
    INNER_ZONE_OFFSET_RATIO: 0.85,
    OUTER_ZONE_OFFSET_RATIO: 0.8,
  },
  ENEMY: {
    BODY_WIDTH: 31,
    BODY_HEIGHT: 36,
    HP_BAR_OFFSET_Y: -25,
    HP_BAR_WIDTH: 23,
    HP_BAR_HEIGHT: 4,
    HIT_FLASH_OFFSET_Y: -3,
  },
} as const;
