export const CombatVfxConfig = {
  SLOT: {
    UPRIGHT_SCALE_BOOST: 0.08,
    ROTATING_SCALE_BOOST: 0.05,
    PAWN_GLOW_SCALE: 1.2,
    EMPTY_GLOW_SCALE: 0.9,
  },
  NOTE_FLIGHT: {
    DURATION_MS: 260,
    ARC_HEIGHT_PX: 28,
    BASE_SCALE: 0.7,
    PEAK_SCALE_BOOST: 0.12,
    END_ALPHA_FALLOFF: 0.15,
  },
  FINISHER: {
    INPUT_STAGGER_MS: 40,
    OUTPUT_DELAY_MS: 60,
  },
  BEAM: {
    DURATION_MS: 130,
    NORMAL_THICKNESS: 8,
    WEAKNESS_THICKNESS: 12,
  },
  ENEMY_HIT: {
    DURATION_MS: 180,
    NORMAL_SCALE_BOOST: 0.2,
    WEAKNESS_SCALE_BOOST: 0.4,
  },
  PACKET_BREAK: {
    DURATION_MS: 220,
    BASE_SCALE: 0.9,
    SCALE_BOOST: 0.45,
  },
  BASE_HIT: {
    DURATION_MS: 240,
    SCALE_BOOST: 0.3,
  },
  RESULT: {
    DURATION_MS: 900,
    SCALE_BOOST: 0.06,
    VICTORY_TINT: 0x63f5a6,
    DEFEAT_TINT: 0xff5f7a,
  },
  TEXTURES: {
    GLOW_SIZE_PX: 128,
    RING_SIZE_PX: 128,
    BEAM_WIDTH_PX: 64,
    BEAM_HEIGHT_PX: 16,
  },
} as const;
