export const StageFlowConfig = {
  INITIAL_COINS: 50,
  WAVE_CLEAR_REWARD_COINS: 15,
  SHOP_OFFER_COUNT: 3,
  SHOP_PURCHASE_COST: 5,
  SHOP_REROLL_BASE_COST: 1,
  REPOSITION_COST: 1,
  MAX_PAWN_TIER: 3,
} as const;
